### ISSUE TITLE
libarry unusable..

### ISSUE THREAD

**Issue by hypericon** [keremciu/sketch-iconfont-web#1]
hi sir,

quite good job, but, which is the logic the icons are displayed?
no search function.. hard to use it this way :/

**Comment by keremciu** [comment]
hello!

@hypericon @esreal12 I wanted to work on this plugin but didn't know people were interested :) I can add search functionality this weekend

**Comment by keremciu** [comment]
I added search functionality! hope this makes the plugin more useful, let's see what's the next big thing :D @hypericon 

![image](https://user-images.githubusercontent.com/1593488/116752587-198b0900-aa06-11eb-8347-7080c67cbb9f.png)
